import { Sequelize, DataTypes } from "sequelize";
import {sequelize} from "../database/database.js"

export const Vehiculos = sequelize.define('vehiculos',{
    vehiculo_id:{
        type:DataTypes.INTEGER,
        primaryKey:true,
        autoIncrement:true
    },
    vehiculo_nombre:{
        type:DataTypes.STRING(20),
        allowNull:false
    },
    vehiculo_anio:{
        type:DataTypes.DATE,
        allowNull:false
    },
    vehiculo_cilindraje:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    vehiculo_potencia:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    vehiculo_velocidad:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    vehiculos_puertas:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    vehiculos_cuatroporcuatro:{
        type:DataTypes.BOOLEAN,
        allowNull:false
    },
    vehiculo_garantia_fecha:{
        type:DataTypes.DATE,
        allowNull:false
    },
    vehiculo_garantia_km:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    vehiculo_tecnologia_uno:{
        type:DataTypes.STRING(30),
        allowNull:false
    },
    vehiculo_tecnologia_dos:{
        type:DataTypes.STRING(30),
        allowNull:false
    },
    vehiculo_tecnologia_tres:{
        type:DataTypes.STRING(30),
        allowNull:false
    },
    vehiculo_tecnologia_cuatro:{
        type:DataTypes.STRING(30),
        allowNull:false
    },
    vehiculo_foto_uno:{
        type:DataTypes.STRING(200),
        allowNull:false
    },
    vehiculo_foto_dos:{
        type:DataTypes.STRING(200),
        allowNull:false
    },
    vehiculo_foto_tres:{
        type:DataTypes.STRING(200),
        allowNull:false
    },
    vehiculo_foto_cuatro:{
        type:DataTypes.STRING(200),
        allowNull:false
    },
    vehiculo_foto_cinco:{
        type:DataTypes.STRING(200),
        allowNull:false
    },
    vehiculo_video:{
        type:DataTypes.STRING(200),
        allowNull:false
    },
    vehiculo_descripcion:{
        type:DataTypes.STRING(300),
        allowNull:false
    },
    vehiculo_categoria_id:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    vehiculo_marca_id:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    vehiculo_tipo_id:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    vehiculo_motor_id:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    vehiculos_trasmision_id:{
        type:DataTypes.INTEGER,
        allowNull:false
    }
})